# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'client'), ('tunga', 'tunga'), ('developer', 'developer')], max_length=150)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='EUR', max_length=15)),
                ('tax_rate', models.IntegerField()),
                ('processing_fee', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=150)),
                ('batch_ref', models.CharField(default=uuid.uuid4, max_length=150)),
                ('tax_amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
