# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='EUR', max_length=15)),
                ('payment_method', models.CharField(choices=[('stripe', 'stripe'), ('bank', 'bank'), ('bitcoin', 'bitcoin'), ('bitonic', 'bitonic')], max_length=150)),
                ('paid_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_invoice', to='tunga_payments.Invoice')),
            ],
        ),
    ]
