# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
    ]
