# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0003_auto_20180525_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices_project', to='tunga_projects.Project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[(b'client', 'Client'), (b'tunga', 'Tunga'), (b'developer', 'Developer')], max_length=150),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[(b'stripe', 'Stripe'), (b'bank', 'Bank Transfer'), (b'bitcoin', 'Bitcoin'), (b'bitonic', 'Bitonic')], max_length=150),
        ),
    ]
