# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0004_auto_20180604_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
