# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0005_invoice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approved',
            field=models.CharField(blank=True, choices=[(b'client', 'Client'), (b'tunga', 'Tunga'), (b'developer', 'Developer')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
