# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0006_auto_20180611_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[(b'pending', 'Pending'), (b'approved', 'Approved'), (b'canceled', 'Canceled')], max_length=150, null=True),
        ),
    ]
