# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0008_auto_20180720_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
    ]
