# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0009_auto_20180720_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-due_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='batch_ref',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
