# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0010_auto_20180720_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='batch_ref',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
