# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import tunga_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0013_auto_20180720_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='btc_address',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[tunga_utils.validators.validate_btc_address_or_none]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[(None, b'Any'), (b'stripe', b'Pay with Stripe'), (b'bitonic', b'Pay with iDeal / mister cash'), (b'bitcoin', b'Pay with BitCoin'), (b'bank', b'Pay by bank transfer')], help_text='None - Any,stripe - Pay with Stripe,bitonic - Pay with iDeal / mister cash,bitcoin - Pay with BitCoin,bank - Pay by bank transfer', max_length=30, null=True),
        ),
    ]
