# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0019_auto_20180720_0053'),
        ('tunga_payments', '0014_auto_20180722_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tunga_projects.ProgressEvent'),
        ),
    ]
