# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0016_auto_20180807_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
