# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 02:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0018_auto_20180810_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issued_at', '-created_at']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='due_at',
            new_name='issued_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
