# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_payments', '0019_auto_20180813_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
