# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0020_invoice_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
