# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0021_auto_20180817_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
