# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0022_invoice_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_note_amount',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='send_credit_note',
            field=models.BooleanField(default=False),
        ),
    ]
