# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-17 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_payments', '0023_auto_20190121_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
