# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0016_blogpost_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillpage',
            old_name='story_body_one',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='skillpage',
            old_name='story_header',
            new_name='content_header',
        ),
        migrations.AddField(
            model_name='skillpage',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/uploads/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='skillpage',
            name='content_sub_header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skillpage',
            name='pitch_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/uploads/%Y/%m/%d'),
        ),
    ]
