# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-09 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0017_auto_20180320_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillpage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='keyword',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='story_body_three',
            field=models.TextField(blank=True, null=True, verbose_name='Content 3'),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='story_body_two',
            field=models.TextField(blank=True, null=True, verbose_name='Content 2'),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='story_interlude_one_cta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='story_interlude_two_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='welcome_header',
            field=models.CharField(max_length=70, verbose_name='Welcome Header H1'),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='welcome_sub_header',
            field=models.CharField(max_length=150, verbose_name='Welcome Subheader'),
        ),
    ]
