# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0018_auto_20180409_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillpage',
            name='pitch_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='welcome_sub_header',
            field=models.TextField(verbose_name='Welcome Subheader'),
        ),
    ]
