# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0020_auto_20180412_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillpage',
            name='pitch_image_alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='keyword',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='URL (slug)'),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='story_interlude_one_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
