# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0140_auto_20171115_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitaskpaymentkey',
            name='payment_method',
            field=models.CharField(blank=True, choices=[(b'ayden', 'Pay with Ayden'), (b'stripe', 'Pay with Stripe'), (b'bitonic', 'Pay with iDeal / mister cash'), (b'bitcoin', 'Pay with BitCoin'), (b'bank', 'Pay by bank transfer')], help_text='ayden - Pay with Ayden,stripe - Pay with Stripe,bitonic - Pay with iDeal / mister cash,bitcoin - Pay with BitCoin,bank - Pay by bank transfer', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_method',
            field=models.CharField(blank=True, choices=[(b'ayden', 'Pay with Ayden'), (b'stripe', 'Pay with Stripe'), (b'bitonic', 'Pay with iDeal / mister cash'), (b'bitcoin', 'Pay with BitCoin'), (b'bank', 'Pay by bank transfer')], help_text='ayden - Pay with Ayden,stripe - Pay with Stripe,bitonic - Pay with iDeal / mister cash,bitcoin - Pay with BitCoin,bank - Pay by bank transfer', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='taskinvoice',
            name='payment_method',
            field=models.CharField(choices=[(b'ayden', 'Pay with Ayden'), (b'stripe', 'Pay with Stripe'), (b'bitonic', 'Pay with iDeal / mister cash'), (b'bitcoin', 'Pay with BitCoin'), (b'bank', 'Pay by bank transfer')], help_text='ayden - Pay with Ayden,stripe - Pay with Stripe,bitonic - Pay with iDeal / mister cash,bitcoin - Pay with BitCoin,bank - Pay by bank transfer', max_length=30),
        ),
    ]
