# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import tunga_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0142_auto_20171212_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinvoice',
            name='btc_address',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[tunga_utils.validators.validate_btc_address_or_none]),
        ),
    ]
