# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0143_auto_20171212_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='distribution_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
