# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0144_task_distribution_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
