# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0145_participantpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpayment',
            name='excludes_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskpayment',
            name='tax_only',
            field=models.BooleanField(default=False),
        ),
    ]
