# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0146_auto_20171215_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpayment',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
