# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0147_taskpayment_amount_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tunga_percentage_dev',
            field=models.DecimalField(decimal_places=9, default=34.21052632, max_digits=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='tunga_percentage_pm',
            field=models.DecimalField(decimal_places=9, default=48.717948717, max_digits=12),
        ),
    ]
