# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-21 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0148_auto_20171220_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
