# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-05 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0149_task_tax_exempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpayment',
            name='payment_type',
            field=models.CharField(choices=[(b'stripe', 'Stripe'), (b'bitcoin', 'BitCoin'), (b'bank', 'Bank Transfer'), (b'payoneer', 'Payoneer')], help_text='stripe - Stripe,bitcoin - BitCoin,bank - Bank Transfer,payoneer - Payoneer', max_length=30),
        ),
    ]
