# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0151_auto_20180113_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dev_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=12.5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pm_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=19, max_digits=19, null=True),
        ),
    ]
