# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0152_auto_20180116_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exclude_payment_costs',
            field=models.BooleanField(default=False),
        ),
    ]
