# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-16 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_tasks', '0152_auto_20180116_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d', verbose_name='Upload')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[(b'estimate', 'Estimate'), (b'proposal', 'Proposal'), (b'planning', 'Planning'), (b'requirements', 'Requirements Document'), (b'wireframes', 'Wireframes'), (b'timeline', 'Timeline'), (b'other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
