# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0154_auto_20180123_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tunga_percentage_dev',
            field=models.DecimalField(decimal_places=9, default=37.5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='tunga_percentage_pm',
            field=models.DecimalField(decimal_places=9, default=100, max_digits=12),
        ),
    ]
