# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-24 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0153_taskdocument'),
        ('tunga_tasks', '0155_auto_20180123_1506'),
    ]

    operations = [
    ]
