# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-24 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0156_merge_20180124_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdocument',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='taskdocument',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='Upload'),
        ),
    ]
