# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0157_auto_20180124_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressevent',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Update'), (2, 'Periodic Update'), (3, 'Milestone'), (4, 'Final Draft'), (5, 'Submission'), (6, 'PM Report'), (8, 'Internal Milestone'), (7, 'Client Survey'), (9, 'MidSprint Client Survey')], default=1, help_text='1 - Update,2 - Periodic Update,3 - Milestone,4 - Final Draft,5 - Submission,6 - PM Report,8 - Internal Milestone,7 - Client Survey,9 - MidSprint Client Survey'),
        ),
    ]
