# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0158_auto_20180208_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='prepaid',
            field=models.NullBooleanField(default=None),
        ),
    ]
