# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-27 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0159_participation_prepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pm_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True),
        ),
    ]
