# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0160_auto_20180227_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinvoice',
            name='version',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
