# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-01 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0162_auto_20180227_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskinvoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='dev_rate',
            field=models.DecimalField(decimal_places=15, default=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='pm_rate',
            field=models.DecimalField(decimal_places=15, default=40, max_digits=30),
        ),
    ]
