# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 18:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0164_auto_20180515_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='rate_communication',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='rate_deliverables',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
