# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0165_auto_20180516_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_projects_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
