# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0166_auto_20180608_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_progress_events_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
