# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0167_auto_20180709_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='stuck_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Resolving an Error'), (2, 'Poor Documentation'), (3, 'Hardware problem'), (4, 'Unclear specifications'), (5, 'Personal Circumstances'), (6, 'Other')], help_text='1 - Resolving an Error,2 - Poor Documentation,3 - Hardware problem,4 - Unclear specifications,5 - Personal Circumstances,6 - Other', null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_progress_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
