# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0168_auto_20180717_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_invoices_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
