# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-23 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0011_auto_20171031_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='disagree_version',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tungauser',
            name='disagreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
