# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0014_auto_20171208_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
