# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0016_auto_20180515_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
