# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0017_tungauser_invoice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tungauser',
            name='source',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Task Wizard'), (3, 'Manual')], default=1),
        ),
    ]
