# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0018_auto_20180912_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tungauser',
            name='payoneer_status',
            field=models.CharField(choices=[(b'initial', 'Initial'), (b'initiated', 'Initiated'), (b'pending', 'Pending'), (b'approved', 'Approved'), (b'declined', 'Decline')], default=b'initial', help_text='initial - Initial, initiated - Initiated, pending - Pending, approved - Approved, declined - Decline', max_length=20),
        ),
    ]
