# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0019_auto_20181017_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvisitor',
            name='via_search',
            field=models.BooleanField(default=False),
        ),
    ]
