# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0020_emailvisitor_via_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='can_pay',
            field=models.BooleanField(default=False),
        ),
    ]
