# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_activity', '0002_fieldchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationReadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'profile', b'Profile'), (b'activity', b'Activity')], max_length=50)),
                ('notification_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationreadlog',
            unique_together=set([('user', 'type', 'notification_id')]),
        ),
    ]
