# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('type', models.CharField(choices=[(b'language', b'Language'), (b'framework', b'Framework'), (b'platform', b'Platform'), (b'library', b'Library'), (b'storage', b'Storage Engine'), (b'api', b'API'), (b'other', b'Other')], default=b'other', help_text='language - Language,framework - Framework,platform - Platform,library - Library,storage - Storage Engine,api - API,other - Other', max_length=30)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('slug',)]),
        ),
    ]
