# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0009_auto_20170413_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
