# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0010_contactrequest_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
