# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-13 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0012_sitemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemeta',
            name='meta_key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
