# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import tunga_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0013_auto_20180413_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d', validators=[tunga_utils.validators.validate_file_size], verbose_name='Upload'),
        ),
    ]
