# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0018_auto_20180813_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviterequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
