# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-15 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0020_externalevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalevent',
            options={'ordering': ['created_at']},
        ),
    ]
