# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0023_auto_20181115_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchevent',
            name='pagination',
            field=models.BooleanField(default=False),
        ),
    ]
