# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0024_searchevent_pagination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchevent',
            name='pagination',
        ),
        migrations.AddField(
            model_name='searchevent',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
