# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=19, null=True)),
                ('currency', models.CharField(choices=[(b'EUR', b'EUR')], default=b'EUR', max_length=5)),
                ('type', models.CharField(choices=[(b'web', b'Web'), (b'mobile', b'Mobile'), (b'other', b'Other')], default=b'other', max_length=20)),
                ('expected_duration', models.CharField(blank=True, choices=[(b'2w', b'2 Weeks'), (b'6m', b'6 Months'), (b'permanent', b'Permanent')], max_length=20, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('client_survey_enabled', models.BooleanField(default=True)),
                ('pm_updates_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='v2_projects_owned', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='v2_projects_managed', to=settings.AUTH_USER_MODEL)),
                ('skills', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='PHP, JavaScript, Python, Ruby, Java, C#, C++, Ruby, Swift, Objective C, .NET, ASP.NET, Node.js,HTML, CSS, HTML5, CSS3, XML, JSON, YAML,Django, Ruby on Rails, Flask, Yii, Lavarel, Express.js, Spring, JAX-RS,AngularJS, React.js, Meteor.js, Ember.js, Backbone.js,WordPress, Joomla, Drupal,jQuery, jQuery UI, Bootstrap, AJAX,Android, iOS, Windows Mobile, Apache Cordova, Ionic,SQL, MySQL, PostgreSQL, MongoDB, CouchDB,Git, Subversion, Mercurial, Docker, Ansible, Webpack, Grunt, Gulp, Ant, Maven, Gradle', space_delimiter=False, to='tunga_skills.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='v2_projects_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
