# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0009_auto_20180709_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
