# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0012_projectmeta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmeta',
            unique_together=set([('project', 'meta_key', 'meta_value')]),
        ),
    ]
