# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0013_auto_20180715_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmeta',
            name='meta_value',
            field=models.TextField(),
        ),
    ]
