# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 15:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_projects', '0015_auto_20180715_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(b'on_schedule', b'On schedule'), (b'behind', b'Behind'), (b'stuck', b'Stuck'), (4, b'Behind but Progressing'), (5, b'Behind and Stuck')], help_text='on_schedule - On schedule,behind - Behind,stuck - Stuck,4 - Behind but Progressing,5 - Behind and Stuck', null=True)),
                ('percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accomplished', models.TextField(blank=True, null=True)),
                ('todo', models.TextField(blank=True, null=True)),
                ('obstacles', models.TextField(blank=True, null=True)),
                ('obstacles_prevention', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('stuck_reason', models.PositiveIntegerField(blank=True, choices=[(b'resolving_error', b'Resolving an Error'), (b'poor_doc', b'Poor Documentation'), (b'hardware_problem', b'Hardware problem'), (b'unclear_spec', b'Unclear specifications'), (b'personal_issue', b'Personal Circumstances'), (b'other', b'Other')], help_text='resolving_error - Resolving an Error,poor_doc - Poor Documentation,hardware_problem - Hardware problem,unclear_spec - Unclear specifications,personal_issue - Personal Circumstances,other - Other', null=True)),
                ('stuck_details', models.TextField(blank=True, null=True)),
                ('rate_deliverables', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_deadline_met', models.NullBooleanField()),
                ('deadline_miss_communicated', models.NullBooleanField()),
                ('deadline_report', models.TextField(blank=True, null=True)),
                ('next_deadline', models.DateTimeField(blank=True, null=True)),
                ('next_deadline_meet', models.NullBooleanField()),
                ('next_deadline_fail_reason', models.TextField(blank=True, null=True)),
                ('team_appraisal', models.TextField(blank=True, null=True)),
                ('deliverable_satisfaction', models.NullBooleanField()),
                ('rate_communication', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pm_communication', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_projects.ProgressEvent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
