# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0016_progressreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='status',
            field=models.CharField(blank=True, choices=[(b'on_schedule', b'On schedule'), (b'behind', b'Behind'), (b'stuck', b'Stuck'), (4, b'Behind but Progressing'), (5, b'Behind and Stuck')], help_text='on_schedule - On schedule,behind - Behind,stuck - Stuck,4 - Behind but Progressing,5 - Behind and Stuck', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='stuck_reason',
            field=models.CharField(blank=True, choices=[(b'resolving_error', b'Resolving an Error'), (b'poor_doc', b'Poor Documentation'), (b'hardware_problem', b'Hardware problem'), (b'unclear_spec', b'Unclear specifications'), (b'personal_issue', b'Personal Circumstances'), (b'other', b'Other')], help_text='resolving_error - Resolving an Error,poor_doc - Poor Documentation,hardware_problem - Hardware problem,unclear_spec - Unclear specifications,personal_issue - Personal Circumstances,other - Other', max_length=50, null=True),
        ),
    ]
