# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0018_auto_20180718_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=17, null=True),
        ),
    ]
