# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_projects', '0021_auto_20180825_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'initial', b'Initial'), (b'accepted', b'Accepted'), (b'rejected', b'Rejected')], default=b'initial', help_text='initial - Initial,interested - Interested,uninterested - Uninterested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_interest_polls_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_interest_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'interest poll',
                'verbose_name_plural': 'interest polls',
            },
        ),
        migrations.AlterUniqueTogether(
            name='interestpoll',
            unique_together=set([('user', 'project')]),
        ),
    ]
