# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0023_auto_20180901_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hubspot_deal_id',
            field=models.CharField(editable=False, max_length=12, null=True),
        ),
    ]
