# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0024_project_hubspot_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestpoll',
            name='approval_status',
            field=models.CharField(choices=[(b'initial', b'Initial'), (b'accepted', b'Accepted'), (b'rejected', b'Rejected')], default=b'initial', help_text='initial - Initial,accepted - Accepted,rejected - Rejected', max_length=20),
        ),
    ]
