# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0025_interestpoll_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestpoll',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interestpoll',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
