# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0031_auto_20171004_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='third_party_apis',
        ),
        migrations.DeleteModel(
            name='Frameworks',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Libraries',
        ),
        migrations.DeleteModel(
            name='Platforms',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='ThirdPartyApis',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
