# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-20 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0031_auto_20171004_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frameworks',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Libraries',
        ),
        migrations.DeleteModel(
            name='Platforms',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='ThirdPartyApis',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='third_party_apis',
        ),
    ]
