# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_profiles', '0032_auto_20180228_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('city', tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, initial='Kampala, Entebbe, Jinja, Nairobi, Mombosa, Dar es Salaam, Kigali, Amsterdam', null=True, on_delete=django.db.models.deletion.CASCADE, space_delimiter=False, to='tunga_profiles.City')),
                ('skills', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='PHP, JavaScript, Python, Ruby, Java, C#, C++, Ruby, Swift, Objective C, .NET, ASP.NET, Node.js,HTML, CSS, HTML5, CSS3, XML, JSON, YAML,Django, Ruby on Rails, Flask, Yii, Lavarel, Express.js, Spring, JAX-RS,AngularJS, React.js, Meteor.js, Ember.js, Backbone.js,WordPress, Joomla, Drupal,jQuery, jQuery UI, Bootstrap, AJAX,Android, iOS, Windows Mobile, Apache Cordova, Ionic,SQL, MySQL, PostgreSQL, MongoDB, CouchDB,Git, Subversion, Mercurial, Docker, Ansible, Webpack, Grunt, Gulp, Ant, Maven, Gradle', space_delimiter=False, to='tunga_profiles.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
