# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0033_auto_20180524_0921'),
        ('tunga_profiles', '0033_company'),
    ]

    operations = [
    ]
