# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 09:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0034_merge_20180615_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, initial='Kampala, Entebbe, Jinja, Nairobi, Mombosa, Dar es Salaam, Kigali, Amsterdam', null=True, on_delete=django.db.models.deletion.CASCADE, space_delimiter=False, to='tunga_profiles.City'),
        ),
    ]
