# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0037_auto_20180709_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='reference_number',
            new_name='ref_no',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
