# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 21:34
from __future__ import unicode_literals
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ('tunga_profiles', '0040_auto_20180911_1327'),
    ]
    operations = [
        migrations.CreateModel(
            name='WhitePaperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
